
toki:
  baseurl:
    backend: ${BACKEND-BASEURL}:${server.port}
    frontend: ${FRONTEND-BASEURL}

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO-CLIENT-ID} #
            client-secret: ${KAKAO-CLIENT-SECRET} #
#            scope: name # 필요한 권한 #
            redirect-uri: ${toki.baseurl.backend}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER-CLIENT-ID}   # REST API 키
            client-secret: ${NAVER-CLIENT-SECRET}
            redirect-uri: ${toki.baseurl.backend}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver,
            scope:
            - name,
            - email
            - profile_image
            - gender
            - age
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt-config:
  secret: ${JWT-SECRET-KEY}
