
# -Dspring.profiles.active=

server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  profiles:
    group:
      local: local
      dev: dev
      prod: prod
    default: local
    active: ${TOKI-BACKEND-ACTIVE:local}
  config:
    import: "application-secret.yml"


logging:
  level:
    root: info
    org:
      apache: debug
      kurento: debug
      springframework: info
      AbstractHandshakeHandler: trace
